# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["oss@fastly.com"]
description = ""
language = "go"
manifest_version = 2
name = "proxy-request-framing"

[local_server]
backends.httpme.url = "https://http-me.glitch.me"
