# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["oss@fastly.com"]
description = ""
language = "go"
manifest_version = 2
name = "early-hints"

[setup.backends.origin]
address = "http-me.fastly.dev"
port = 443
